/* eslint-disable react/prop-types, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useMutation } from "@tanstack/react-query";
import { Icon } from "@iconify/react";
import { useAuth } from "../libs/hooks/use-auth";
import heroImage from "../assets/brand/hero-pro-player.png";

function AuthShell({mode,children}){return <main className="authV3"><section><Link className="authBack" to="/"><Icon icon="solar:arrow-left-linear"/> ATP website</Link><div><p>ATP PLAYER ACCOUNT</p><h1>{mode==="login"?"Welcome back.":"Join the club."}</h1><span>{mode==="login"?"Your training, tournaments and tennis community are waiting.":"Create your player profile and put everything ATP in one place."}</span>{children}</div></section><aside><img src={heroImage} alt="Professional tennis player"/><span/><div><small>PLAY · TRAIN · BELONG</small><h2>Own your next point.</h2></div></aside></main>}
export function Login(){const navigate=useNavigate();const location=useLocation();const {isAuthenticated,userLogin}=useAuth();const [payload,setPayload]=useState({email:"",password:""});const [error,setError]=useState("");useEffect(()=>{isAuthenticated().then(auth=>auth&&navigate(new URLSearchParams(location.search).get("redirect")||"/u"))},[]);const login=useMutation({mutationFn:userLogin,onSuccess:()=>navigate(new URLSearchParams(location.search).get("redirect")||"/u"),onError:err=>setError(err.response?.data?.message||"We could not sign you in.")});const submit=e=>{e.preventDefault();setError("");login.mutate(payload)};return <AuthShell mode="login"><form className="authFormV3" onSubmit={submit}><label>Email<input required type="email" value={payload.email} onChange={e=>setPayload({...payload,email:e.target.value.toLowerCase()})} placeholder="you@example.com"/></label><label>Password<input required type="password" value={payload.password} onChange={e=>setPayload({...payload,password:e.target.value})} placeholder="Your password"/></label>{error&&<p className="formMessage error">{error}</p>}<button disabled={login.isPending}>{login.isPending?"Signing in…":"Sign in"}<Icon icon="solar:arrow-right-linear"/></button></form><div className="authLinks"><Link to="/forgot-password">Forgot password?</Link><span>New to ATP? <Link to="/signup">Create an account</Link></span></div></AuthShell>}
export function SignUp(){const navigate=useNavigate();const location=useLocation();const {isAuthenticated,userRegister}=useAuth();const [payload,setPayload]=useState({fullName:"",email:"",username:"",password:"",dob:"",phoneNumber:"",role:"",level:""});const [error,setError]=useState("");useEffect(()=>{isAuthenticated().then(auth=>auth&&navigate("/u"))},[]);const signup=useMutation({mutationFn:userRegister,onSuccess:()=>{const redirect=new URLSearchParams(location.search).get("redirect");navigate(redirect?`/login?redirect=${encodeURIComponent(redirect)}`:"/login")},onError:err=>setError(err.response?.data?.message||"Your account could not be created.")});const change=e=>setPayload({...payload,[e.target.name]:e.target.name==="email"?e.target.value.toLowerCase():e.target.value});const submit=e=>{e.preventDefault();setError("");signup.mutate(payload)};return <AuthShell mode="signup"><form className="authFormV3 signup" onSubmit={submit}><label>Full name<input required name="fullName" value={payload.fullName} onChange={change}/></label><label>Username<input required name="username" pattern="^[a-zA-Z0-9_]+$" value={payload.username} onChange={change}/></label><label>Email<input required type="email" name="email" value={payload.email} onChange={change}/></label><label>Phone<input required type="tel" name="phoneNumber" value={payload.phoneNumber} onChange={change}/></label><label>Password<input required type="password" name="password" value={payload.password} onChange={change}/></label><label>Date of birth<input required type="date" name="dob" value={payload.dob} onChange={change}/></label><label>Role<select required name="role" value={payload.role} onChange={change}><option value="">Select role</option><option value="student">Player</option><option value="coach">Coach</option></select></label><label>Playing level<select required name="level" value={payload.level} onChange={change}><option value="">Select level</option><option value="kids amatuer">Junior foundation</option><option value="kids mid-level">Junior developing</option><option value="kids professional">Junior performance</option><option value="adult amatuer">Adult foundation</option><option value="adult mid-level">Adult developing</option><option value="adult professional">Adult performance</option></select></label>{error&&<p className="formMessage error">{error}</p>}<button disabled={signup.isPending}>{signup.isPending?"Creating account…":"Create player account"}<Icon icon="solar:arrow-right-linear"/></button></form><div className="authLinks"><span>Already a member? <Link to="/login">Sign in</Link></span></div></AuthShell>}
