import { Icon } from "@iconify/react";
import { useCopy, Lines } from "../libs/hooks/use-copy";
import { AtpButton, PageHero, Reveal, SectionHeading } from "../components/system/system";
import heroImage from "../assets/brand/pro-serve.jpg";
import youthImage from "../assets/brand/youth-training.jpg";
import communityImage from "../assets/brand/club-community.jpg";

const lessons=[{title:"Build a reliable backhand",level:"Adult · Foundation",time:"08:24",image:heroImage},{title:"Serve rhythm without rushing",level:"Performance",time:"11:10",image:communityImage},{title:"First rally fundamentals",level:"Junior · Foundation",time:"06:42",image:youthImage}];
export default function Videos(){const copy=useCopy();return <main className="editorialPage videosV3"><PageHero eyebrow={copy("videos.hero.eyebrow","ATP video room")} title={<Lines>{copy("videos.hero.title","Learn. Rewatch.\nTake it to court.")}</Lines>} text={copy("videos.hero.text","Short, practical lessons designed to make the next training session more useful.")} image={heroImage} actions={<AtpButton to="/coaching">{copy("videos.hero.cta","Train with a coach")}</AtpButton>}/><section className="lessonShelf pagePad"><SectionHeading eyebrow={copy("videos.library.eyebrow","Instructional library")} title={copy("videos.library.title","Start with one detail.")} text={copy("videos.library.text","Choose a lesson, take one cue to court and repeat until it feels natural.")}/><div className="lessonFilters"><button className="active">All lessons</button><button>Juniors</button><button>Adult foundation</button><button>Performance</button></div><div className="lessonGrid">{lessons.map((lesson,index)=><Reveal key={lesson.title} delay={index*80}><article className="lessonCard"><div><img src={lesson.image} alt=""/><button aria-label={`Play ${lesson.title}`}><Icon icon="solar:play-bold"/></button><time>{lesson.time}</time></div><small>{lesson.level}</small><h2>{lesson.title}</h2><p>Coach-led cues, a clear demonstration and one drill to practise next.</p></article></Reveal>)}</div></section><section className="videoNote"><Icon icon="solar:videocamera-record-linear"/><div><small>{copy("videos.note.eyebrow","MORE LESSONS ARE COMING")}</small><h2>{copy("videos.note.title","A library that grows with your game.")}</h2></div><AtpButton to="/contact" variant="ghost">{copy("videos.note.cta","Request a topic")}</AtpButton></section></main>}
