/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminBillingsRouteImport } from './routes/_admin/billings'
import { Route as AdminCmsRouteImport } from './routes/_admin/cms'
import { Route as AdminCoachesRouteImport } from './routes/_admin/coaches'
import { Route as AdminCommunityRouteImport } from './routes/_admin/community'
import { Route as AdminContentRouteImport } from './routes/_admin/content'
import { Route as AdminCustomMatchesRouteImport } from './routes/_admin/customMatches'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminEngagementRouteImport } from './routes/_admin/engagement'
import { Route as AdminGalleryRouteImport } from './routes/_admin/gallery'
import { Route as AdminLeaderboardRouteImport } from './routes/_admin/leaderboard'
import { Route as AdminLinkedPlayersRouteImport } from './routes/_admin/linkedPlayers'
import { Route as AdminMatchesRouteImport } from './routes/_admin/matches'
import { Route as AdminPlanRouteImport } from './routes/_admin/plan'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminStoreRouteImport } from './routes/_admin/store'
import { Route as AdminSubscriptionsRouteImport } from './routes/_admin/subscriptions'
import { Route as AdminTournamentsRouteImport } from './routes/_admin/tournaments'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AuthCreateAdminRouteImport } from './routes/_auth/createAdmin'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgotPassword'
import { Route as AdminCmsNewRouteImport } from './routes/_admin/cms_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingsRoute = AdminBillingsRouteImport.update({
  id: '/billings',
  path: '/billings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomMatchesRoute = AdminCustomMatchesRouteImport.update({
  id: '/customMatches',
  path: '/customMatches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngagementRoute = AdminEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinkedPlayersRoute = AdminLinkedPlayersRouteImport.update({
  id: '/linkedPlayers',
  path: '/linkedPlayers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanRoute = AdminPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCreateAdminRoute = AuthCreateAdminRouteImport.update({
  id: '/_auth/createAdmin',
  path: '/createAdmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsNewRoute = AdminCmsNewRouteImport.update({
  id: '/cms_/new',
  path: '/cms/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billings': typeof AdminBillingsRoute
  '/cms': typeof AdminCmsRoute
  '/coaches': typeof AdminCoachesRoute
  '/community': typeof AdminCommunityRoute
  '/content': typeof AdminContentRoute
  '/customMatches': typeof AdminCustomMatchesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/engagement': typeof AdminEngagementRoute
  '/gallery': typeof AdminGalleryRoute
  '/leaderboard': typeof AdminLeaderboardRoute
  '/linkedPlayers': typeof AdminLinkedPlayersRoute
  '/matches': typeof AdminMatchesRoute
  '/plan': typeof AdminPlanRoute
  '/settings': typeof AdminSettingsRoute
  '/store': typeof AdminStoreRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/tournaments': typeof AdminTournamentsRoute
  '/users': typeof AdminUsersRoute
  '/createAdmin': typeof AuthCreateAdminRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/cms/new': typeof AdminCmsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billings': typeof AdminBillingsRoute
  '/cms': typeof AdminCmsRoute
  '/coaches': typeof AdminCoachesRoute
  '/community': typeof AdminCommunityRoute
  '/content': typeof AdminContentRoute
  '/customMatches': typeof AdminCustomMatchesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/engagement': typeof AdminEngagementRoute
  '/gallery': typeof AdminGalleryRoute
  '/leaderboard': typeof AdminLeaderboardRoute
  '/linkedPlayers': typeof AdminLinkedPlayersRoute
  '/matches': typeof AdminMatchesRoute
  '/plan': typeof AdminPlanRoute
  '/settings': typeof AdminSettingsRoute
  '/store': typeof AdminStoreRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/tournaments': typeof AdminTournamentsRoute
  '/users': typeof AdminUsersRoute
  '/createAdmin': typeof AuthCreateAdminRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/cms/new': typeof AdminCmsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/billings': typeof AdminBillingsRoute
  '/_admin/cms': typeof AdminCmsRoute
  '/_admin/coaches': typeof AdminCoachesRoute
  '/_admin/community': typeof AdminCommunityRoute
  '/_admin/content': typeof AdminContentRoute
  '/_admin/customMatches': typeof AdminCustomMatchesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/engagement': typeof AdminEngagementRoute
  '/_admin/gallery': typeof AdminGalleryRoute
  '/_admin/leaderboard': typeof AdminLeaderboardRoute
  '/_admin/linkedPlayers': typeof AdminLinkedPlayersRoute
  '/_admin/matches': typeof AdminMatchesRoute
  '/_admin/plan': typeof AdminPlanRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/store': typeof AdminStoreRoute
  '/_admin/subscriptions': typeof AdminSubscriptionsRoute
  '/_admin/tournaments': typeof AdminTournamentsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_auth/createAdmin': typeof AuthCreateAdminRoute
  '/_auth/forgotPassword': typeof AuthForgotPasswordRoute
  '/_admin/cms_/new': typeof AdminCmsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billings'
    | '/cms'
    | '/coaches'
    | '/community'
    | '/content'
    | '/customMatches'
    | '/dashboard'
    | '/engagement'
    | '/gallery'
    | '/leaderboard'
    | '/linkedPlayers'
    | '/matches'
    | '/plan'
    | '/settings'
    | '/store'
    | '/subscriptions'
    | '/tournaments'
    | '/users'
    | '/createAdmin'
    | '/forgotPassword'
    | '/cms/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billings'
    | '/cms'
    | '/coaches'
    | '/community'
    | '/content'
    | '/customMatches'
    | '/dashboard'
    | '/engagement'
    | '/gallery'
    | '/leaderboard'
    | '/linkedPlayers'
    | '/matches'
    | '/plan'
    | '/settings'
    | '/store'
    | '/subscriptions'
    | '/tournaments'
    | '/users'
    | '/createAdmin'
    | '/forgotPassword'
    | '/cms/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/billings'
    | '/_admin/cms'
    | '/_admin/coaches'
    | '/_admin/community'
    | '/_admin/content'
    | '/_admin/customMatches'
    | '/_admin/dashboard'
    | '/_admin/engagement'
    | '/_admin/gallery'
    | '/_admin/leaderboard'
    | '/_admin/linkedPlayers'
    | '/_admin/matches'
    | '/_admin/plan'
    | '/_admin/settings'
    | '/_admin/store'
    | '/_admin/subscriptions'
    | '/_admin/tournaments'
    | '/_admin/users'
    | '/_auth/createAdmin'
    | '/_auth/forgotPassword'
    | '/_admin/cms_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthCreateAdminRoute: typeof AuthCreateAdminRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/billings': {
      id: '/_admin/billings'
      path: '/billings'
      fullPath: '/billings'
      preLoaderRoute: typeof AdminBillingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cms': {
      id: '/_admin/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/coaches': {
      id: '/_admin/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/community': {
      id: '/_admin/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/content': {
      id: '/_admin/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customMatches': {
      id: '/_admin/customMatches'
      path: '/customMatches'
      fullPath: '/customMatches'
      preLoaderRoute: typeof AdminCustomMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/engagement': {
      id: '/_admin/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof AdminEngagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/gallery': {
      id: '/_admin/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/leaderboard': {
      id: '/_admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/linkedPlayers': {
      id: '/_admin/linkedPlayers'
      path: '/linkedPlayers'
      fullPath: '/linkedPlayers'
      preLoaderRoute: typeof AdminLinkedPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/matches': {
      id: '/_admin/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plan': {
      id: '/_admin/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AdminPlanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/store': {
      id: '/_admin/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subscriptions': {
      id: '/_admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tournaments': {
      id: '/_admin/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/createAdmin': {
      id: '/_auth/createAdmin'
      path: '/createAdmin'
      fullPath: '/createAdmin'
      preLoaderRoute: typeof AuthCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgotPassword': {
      id: '/_auth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/cms_/new': {
      id: '/_admin/cms_/new'
      path: '/cms/new'
      fullPath: '/cms/new'
      preLoaderRoute: typeof AdminCmsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingsRoute: typeof AdminBillingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomMatchesRoute: typeof AdminCustomMatchesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEngagementRoute: typeof AdminEngagementRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLinkedPlayersRoute: typeof AdminLinkedPlayersRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminPlanRoute: typeof AdminPlanRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminCmsNewRoute: typeof AdminCmsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingsRoute: AdminBillingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomMatchesRoute: AdminCustomMatchesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEngagementRoute: AdminEngagementRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLinkedPlayersRoute: AdminLinkedPlayersRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminPlanRoute: AdminPlanRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminCmsNewRoute: AdminCmsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthCreateAdminRoute: AuthCreateAdminRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
