/* eslint-disable react/prop-types */
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Icon } from "@iconify/react";
import { getCommunityTopic, getCommunityTopics, getEngagementItems, postCommunityComment, respondToEngagement } from "../../libs/api/api.endpoints";
const participantId=()=>{let id=localStorage.getItem("atp-participant-id");if(!id){id=crypto.randomUUID();localStorage.setItem("atp-participant-id",id)}return id};
export default function PlayerCommunity(){const [tab,setTab]=useState("talk");const [topicId,setTopicId]=useState(null);const topics=useQuery({queryKey:["community-topics"],queryFn:getCommunityTopics});const engagement=useQuery({queryKey:["engagement"],queryFn:getEngagementItems});return <main className="dashCommunity"><header><p>ATP CLUBHOUSE</p><h1>Talk tennis.<br/>Call the shot.</h1><span>The community is now part of your player desk.</span></header><nav><button className={tab==="talk"?"active":""} onClick={()=>{setTab("talk");setTopicId(null)}}><Icon icon="solar:chat-round-dots-linear"/>Discussions</button><button className={tab==="play"?"active":""} onClick={()=>setTab("play")}><Icon icon="solar:question-circle-linear"/>Quiz & polls</button></nav>{tab==="talk"?(topicId?<DashThread id={topicId} back={()=>setTopicId(null)}/>:<section className="dashTopics">{topics.data?.map(topic=><button key={topic._id} onClick={()=>setTopicId(topic._id)}><span>{topic.pinned?<Icon icon="solar:pin-linear"/>:<Icon icon="solar:chat-line-linear"/>}</span><div><small>{topic.tag}</small><h2>{topic.title}</h2><p>{topic.prompt}</p></div><strong>{topic.replyCount}<small>replies</small></strong></button>)}</section>):<section className="dashChallenges">{engagement.data?.map(item=><DashChallenge key={item._id} item={item}/>)}</section>}</main>}
function DashThread({id,back}){const qc=useQueryClient();const [body,setBody]=useState("");const [parentId,setParentId]=useState(null);const {data}=useQuery({queryKey:["community-topic",id],queryFn:()=>getCommunityTopic(id)});const post=useMutation({mutationFn:postCommunityComment,onSuccess:()=>{setBody("");setParentId(null);qc.invalidateQueries({queryKey:["community-topic",id]})}});return <section className="dashThread"><button onClick={back}><Icon icon="solar:arrow-left-linear"/>All discussions</button><header><small>{data?.topic?.tag}</small><h2>{data?.topic?.title}</h2><p>{data?.topic?.prompt}</p></header><form onSubmit={e=>{e.preventDefault();post.mutate({topicId:id,body,parentId})}}><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={parentId?"Write your reply…":"Add your view…"}/><div>{parentId&&<button type="button" onClick={()=>setParentId(null)}>Cancel reply</button>}<button disabled={!body.trim()||post.isPending}>{post.isPending?"Posting…":"Post response"}</button></div></form><div>{data?.comments?.filter(comment=>!comment.parent).map(comment=><article key={comment._id}><span>{(comment.author?.fullName||"P").charAt(0)}</span><div><header><strong>{comment.author?.fullName||comment.author?.username}</strong><time>{new Date(comment.createdAt).toLocaleDateString()}</time></header><p>{comment.status==="removed"?"Response removed by moderator.":comment.body}</p>{comment.status!=="removed"&&<button onClick={()=>setParentId(comment._id)}>Reply</button>}{data.comments.filter(reply=>String(reply.parent)===String(comment._id)).map(reply=><aside key={reply._id}><strong>{reply.author?.fullName||reply.author?.username}</strong><p>{reply.status==="removed"?"Reply removed by moderator.":reply.body}</p></aside>)}</div></article>)}</div></section>}
function DashChallenge({item}){const [result,setResult]=useState(null);const vote=useMutation({mutationFn:respondToEngagement,onSuccess:setResult});const options=result?.result.options||item.options;const total=result?options.reduce((sum,o)=>sum+o.votes,0):item.totalResponses;return <article><header><span>{item.kind}</span><small>{total} responses</small></header><h2>{item.question}</h2><div>{options.map(option=>{const percentage=total?Math.round(option.votes/total*100):0;return <button key={option._id} disabled={!!result} onClick={()=>vote.mutate({id:item._id,optionId:option._id,participantId:participantId()})}><span>{option.label}</span>{result&&<strong>{percentage}%</strong>}</button>})}</div>{result&&<p>{result.message} {result.result.explanation}</p>}</article>}
