import { createCommunityTopic, deleteCommunityTopic, getCommunityCommentsAdmin, getCommunityTopicsAdmin, moderateCommunityComment, updateCommunityTopic } from '@/apis/endpoints'
import Header from '@/components/blocks/header/header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import { Eye, EyeOff, MessageSquare, Pencil, Pin, Plus, Trash2, X } from 'lucide-react'
import { useState } from 'react'

export const Route = createFileRoute('/_admin/community')({ component: CommunityManager })
const blank={title:'',prompt:'',tag:'Open court',status:'draft',pinned:false}
function CommunityManager(){
 const qc=useQueryClient(); const [tab,setTab]=useState<'topics'|'moderation'>('topics'); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>(blank)
 const {data:topics=[]}=useQuery({queryKey:['admin-community-topics'],queryFn:getCommunityTopicsAdmin}); const {data:comments=[]}=useQuery({queryKey:['admin-community-comments'],queryFn:getCommunityCommentsAdmin})
 const refresh=()=>qc.invalidateQueries({queryKey:['admin-community-topics']}); const save=useMutation({mutationFn:(payload:any)=>editing?updateCommunityTopic({id:editing._id,payload}):createCommunityTopic(payload),onSuccess:()=>{refresh();setEditing(null);setForm(blank)}}); const remove=useMutation({mutationFn:deleteCommunityTopic,onSuccess:refresh}); const moderate=useMutation({mutationFn:moderateCommunityComment,onSuccess:()=>qc.invalidateQueries({queryKey:['admin-community-comments']})})
 const open=(topic?:any)=>{setEditing(topic||{new:true});setForm(topic?{...topic}:blank)}
 return <div className="p-6 md:p-10 max-w-7xl mx-auto"><Header title="Community" subText="Lead clubhouse conversations and moderate member responses"><Button onClick={()=>open()}><Plus className="h-4 w-4 mr-2"/>New discussion</Button></Header>
 <div className="flex gap-2 mt-8 border-b"><button className={`px-4 py-3 text-sm font-semibold ${tab==='topics'?'border-b-2 border-primary':''}`} onClick={()=>setTab('topics')}>Discussions</button><button className={`px-4 py-3 text-sm font-semibold ${tab==='moderation'?'border-b-2 border-primary':''}`} onClick={()=>setTab('moderation')}>Moderation ({comments.filter((c:any)=>c.status==='visible').length})</button></div>
 {editing&&<form className="mt-6 border rounded-xl bg-card p-6 grid gap-4" onSubmit={e=>{e.preventDefault();save.mutate(form)}}><div className="flex justify-between"><h2 className="font-semibold text-xl">{editing.new?'Start a discussion':'Edit discussion'}</h2><Button type="button" variant="ghost" size="icon" onClick={()=>setEditing(null)}><X/></Button></div><label className="grid gap-2 text-sm">Discussion title<Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="grid gap-2 text-sm">Prompt<Textarea required value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})}/></label><div className="grid md:grid-cols-3 gap-4"><label className="grid gap-2 text-sm">Topic label<Input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})}/></label><label className="grid gap-2 text-sm">Status<select className="border rounded-md px-3 py-2 bg-background" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="locked">Locked</option></select></label><label className="flex gap-2 items-end pb-2"><input type="checkbox" checked={form.pinned} onChange={e=>setForm({...form,pinned:e.target.checked})}/> Pin discussion</label></div><div className="flex justify-end"><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save discussion'}</Button></div></form>}
 {tab==='topics'?<div className="grid gap-3 mt-6">{topics.map((topic:any)=><article className="border rounded-xl bg-card p-5 flex gap-4 items-center" key={topic._id}>{topic.pinned?<Pin className="text-primary"/>:<MessageSquare className="text-muted-foreground"/>}<div className="flex-1"><div className="flex gap-2"><span className="text-xs text-primary font-semibold">{topic.tag}</span><span className="text-xs text-muted-foreground">{topic.status}</span></div><h3 className="font-semibold">{topic.title}</h3><p className="text-sm text-muted-foreground">{topic.replyCount} replies</p></div><Button variant="outline" size="sm" onClick={()=>open(topic)}><Pencil className="h-4 w-4 mr-2"/>Edit</Button><Button variant="ghost" size="icon" onClick={()=>confirm('Delete this discussion and its replies?')&&remove.mutate(topic._id)}><Trash2 className="h-4 w-4"/></Button></article>)}</div>:<div className="grid gap-3 mt-6">{comments.map((comment:any)=><article className={`border rounded-xl p-5 flex gap-4 ${comment.status==='removed'?'bg-muted opacity-70':'bg-card'}`} key={comment._id}><div className="flex-1"><p className="text-xs text-primary font-semibold">{comment.topic?.title||'Deleted discussion'} · {comment.author?.fullName||comment.author?.username||'Member'}</p><p className="mt-2">{comment.body}</p><small className="text-muted-foreground">{new Date(comment.createdAt).toLocaleString()}</small></div><Button variant="outline" size="sm" onClick={()=>moderate.mutate({id:comment._id,status:comment.status==='visible'?'removed':'visible'})}>{comment.status==='visible'?<><EyeOff className="h-4 w-4 mr-2"/>Remove</>:<><Eye className="h-4 w-4 mr-2"/>Restore</>}</Button></article>)}</div>}</div>
}
