import { createEngagement, deleteEngagement, getEngagementAdmin, updateEngagement } from '@/apis/endpoints'
import Header from '@/components/blocks/header/header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import { BarChart3, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useState } from 'react'

export const Route = createFileRoute('/_admin/engagement')({ component: EngagementManager })
const blank={kind:'poll',question:'',kicker:'Clubhouse question',explanation:'',status:'draft',featured:false,options:[{label:'',isCorrect:false},{label:'',isCorrect:false}]}

function EngagementManager(){
 const qc=useQueryClient(); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>(blank)
 const {data:items=[],isLoading}=useQuery({queryKey:['admin-engagement'],queryFn:getEngagementAdmin})
 const refresh=()=>qc.invalidateQueries({queryKey:['admin-engagement']})
 const save=useMutation({mutationFn:(payload:any)=>editing?updateEngagement({id:editing._id,payload}):createEngagement(payload),onSuccess:()=>{refresh();setEditing(null);setForm(blank)}})
 const remove=useMutation({mutationFn:deleteEngagement,onSuccess:refresh})
 const open=(item?:any)=>{setEditing(item||{new:true});setForm(item?{...item,options:item.options.map((o:any)=>({...o}))}:{...blank,options:blank.options.map(o=>({...o}))})}
 const option=(index:number,key:string,value:any)=>setForm({...form,options:form.options.map((o:any,i:number)=>i===index?{...o,[key]:value,...(key==='isCorrect'&&value?{}:{})}:key==='isCorrect'&&value?{...o,isCorrect:false}:o)})
 const submit=(e:any)=>{e.preventDefault();save.mutate(form)}
 return <div className="p-6 md:p-10 max-w-7xl mx-auto"><Header title="Quiz & polls" subText="Publish quick tennis challenges and follow participation"><Button onClick={()=>open()}><Plus className="h-4 w-4 mr-2"/>New challenge</Button></Header>
 {editing&&<form onSubmit={submit} className="mt-8 border rounded-xl bg-card p-6 grid gap-4"><div className="flex justify-between"><h2 className="text-xl font-semibold">{editing.new?'Create challenge':'Edit challenge'}</h2><Button type="button" variant="ghost" size="icon" onClick={()=>setEditing(null)}><X/></Button></div><div className="grid md:grid-cols-3 gap-4"><label className="grid gap-2 text-sm">Type<select className="border rounded-md px-3 py-2 bg-background" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="poll">Poll</option><option value="quiz">Quiz</option></select></label><label className="grid gap-2 text-sm">Status<select className="border rounded-md px-3 py-2 bg-background" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select></label><label className="flex gap-2 items-end pb-2"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Feature this challenge</label></div><label className="grid gap-2 text-sm">Short label<Input value={form.kicker} onChange={e=>setForm({...form,kicker:e.target.value})}/></label><label className="grid gap-2 text-sm">Question<Textarea required value={form.question} onChange={e=>setForm({...form,question:e.target.value})}/></label><div className="grid gap-3"><strong className="text-sm">Answer options</strong>{form.options.map((o:any,i:number)=><div className="flex gap-3 items-center" key={i}><Input required value={o.label} placeholder={`Option ${i+1}`} onChange={e=>option(i,'label',e.target.value)}/>{form.kind==='quiz'&&<label className="flex gap-2 text-sm whitespace-nowrap"><input type="radio" name="correct" checked={o.isCorrect} onChange={()=>option(i,'isCorrect',true)}/> Correct</label>}{form.options.length>2&&<Button type="button" variant="ghost" size="icon" onClick={()=>setForm({...form,options:form.options.filter((_:any,n:number)=>n!==i)})}><X/></Button>}</div>)}<Button type="button" variant="outline" className="w-fit" onClick={()=>setForm({...form,options:[...form.options,{label:'',isCorrect:false}]})}>Add option</Button></div><label className="grid gap-2 text-sm">Explanation shown after answering<Textarea value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})}/></label><div className="flex justify-end"><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save challenge'}</Button></div></form>}
 <div className="grid gap-3 mt-8">{isLoading&&<p>Loading challenges…</p>}{items.map((item:any)=><article className="border rounded-xl bg-card p-5 flex gap-4 items-start" key={item._id}><div className="h-12 w-12 rounded-full bg-muted grid place-items-center shrink-0"><BarChart3/></div><div className="flex-1"><div className="flex gap-2"><span className="text-xs uppercase font-semibold text-primary">{item.kind}</span><span className="text-xs text-muted-foreground">{item.status}</span></div><h3 className="font-semibold mt-1">{item.question}</h3><p className="text-sm text-muted-foreground">{item.totalResponses} responses · {item.options.length} options</p><div className="flex flex-wrap gap-2 mt-3">{item.options.map((option:any)=><span className="text-xs border rounded-full px-3 py-1" key={option._id}>{option.label}: <strong>{option.votes}</strong>{item.kind==='quiz'&&option.isCorrect?' · correct':''}</span>)}</div></div><Button variant="outline" size="sm" onClick={()=>open(item)}><Pencil className="h-4 w-4 mr-2"/>Edit</Button><Button variant="ghost" size="icon" onClick={()=>confirm('Delete this challenge?')&&remove.mutate(item._id)}><Trash2 className="h-4 w-4"/></Button></article>)}</div></div>
}
