import { archiveStoreProduct, createStoreProduct, getStoreOverview, updateStoreOrderStatus, updateStoreProduct } from '@/apis/endpoints'
import Header from '@/components/blocks/header/header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useCloudinary } from '@/hooks/use-cloudinary'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import { Archive, ImagePlus, PackagePlus, Pencil, X } from 'lucide-react'
import { useState } from 'react'

export const Route = createFileRoute('/_admin/store')({ component: StoreManager })
const empty={name:'',category:'Gear',description:'',price:'',stock:'',images:[] as string[],active:true}
const money=(value:number)=>`₦${Number(value||0).toLocaleString()}`

function StoreManager(){
 const qc=useQueryClient(),{uploadFile}=useCloudinary(); const [tab,setTab]=useState<'products'|'orders'>('products'); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>(empty); const [uploading,setUploading]=useState(false)
 const {data={products:[],orders:[],revenue:0,paidOrders:0},isLoading}=useQuery({queryKey:['store-overview'],queryFn:getStoreOverview})
 const refresh=()=>qc.invalidateQueries({queryKey:['store-overview']})
 const save=useMutation({mutationFn:(payload:any)=>editing?updateStoreProduct({id:editing._id,payload}):createStoreProduct(payload),onSuccess:()=>{refresh();setEditing(null);setForm(empty)}})
 const archive=useMutation({mutationFn:archiveStoreProduct,onSuccess:refresh}); const status=useMutation({mutationFn:updateStoreOrderStatus,onSuccess:refresh})
 const edit=(product:any)=>{setEditing(product);setForm({...product,price:String(product.price),stock:String(product.stock)})}
 const upload=async(file:File|null)=>{setUploading(true);try{const url=await uploadFile(file);if(url)setForm((old:any)=>({...old,images:[...old.images,url]}))}finally{setUploading(false)}}
 const submit=(e:any)=>{e.preventDefault();save.mutate({...form,price:Number(form.price),stock:Number(form.stock)})}
 const lowStock=data.products.filter((p:any)=>p.active&&p.stock<=5).length
 return <div className="p-6 md:p-10 max-w-7xl mx-auto">
  <Header title="ATP Store" subText="Manage merchandise, stock, payments and order fulfilment"><Button onClick={()=>{setEditing({new:true});setForm(empty)}}><PackagePlus className="h-4 w-4 mr-2"/>Add product</Button></Header>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-8">{[['Products',data.products.length],['Low stock',lowStock],['Paid orders',data.paidOrders],['Revenue',money(data.revenue)]].map(([label,value])=><div className="border rounded-xl p-5 bg-card" key={label}><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><strong className="text-2xl mt-2 block">{value}</strong></div>)}</div>
  <div className="flex gap-2 mt-8 border-b"><button className={`px-4 py-3 text-sm font-semibold ${tab==='products'?'border-b-2 border-primary':''}`} onClick={()=>setTab('products')}>Products & stock</button><button className={`px-4 py-3 text-sm font-semibold ${tab==='orders'?'border-b-2 border-primary':''}`} onClick={()=>setTab('orders')}>Orders</button></div>
  {editing&&<form onSubmit={submit} className="mt-6 border rounded-xl p-6 bg-card grid md:grid-cols-2 gap-4"><div className="md:col-span-2 flex justify-between"><h2 className="text-xl font-semibold">{editing.new?'Add product':'Edit product'}</h2><Button type="button" variant="ghost" size="icon" onClick={()=>setEditing(null)}><X/></Button></div><label className="grid gap-2 text-sm">Product name<Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="grid gap-2 text-sm">Category<Input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="grid gap-2 text-sm">Price (₦)<Input required min="0" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label className="grid gap-2 text-sm">Stock count<Input required min="0" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="grid gap-2 text-sm md:col-span-2">Description<Textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="md:col-span-2"><p className="text-sm mb-2">Product images</p><div className="flex gap-3 flex-wrap">{form.images.map((image:string,index:number)=><div className="relative" key={image}><img src={image} className="h-24 w-24 object-cover rounded border"/><button type="button" className="absolute -top-2 -right-2 bg-black text-white rounded-full w-6 h-6" onClick={()=>setForm({...form,images:form.images.filter((_:string,i:number)=>i!==index)})}>×</button></div>)}<label className="h-24 w-24 border border-dashed rounded grid place-items-center cursor-pointer"><ImagePlus/><input className="hidden" type="file" accept="image/*" disabled={uploading} onChange={e=>upload(e.target.files?.[0]||null)}/></label></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Visible in shop</label><div className="flex justify-end"><Button disabled={save.isPending||uploading}>{save.isPending?'Saving…':'Save product'}</Button></div></form>}
  {isLoading?<p className="py-12">Loading store…</p>:tab==='products'?<div className="mt-6 grid gap-3">{data.products.map((p:any)=><article className="border rounded-xl p-4 bg-card flex items-center gap-4" key={p._id}>{p.images?.[0]?<img src={p.images[0]} className="w-20 h-20 object-cover rounded"/>:<div className="w-20 h-20 bg-muted grid place-items-center font-bold">ATP</div>}<div className="flex-1"><div className="flex items-center gap-2"><h3 className="font-semibold">{p.name}</h3>{!p.active&&<span className="text-xs bg-muted px-2 py-1 rounded">Archived</span>}</div><p className="text-sm text-muted-foreground">{p.category} · {money(p.price)}</p><p className={`text-sm font-semibold mt-1 ${p.stock<=5?'text-orange-600':''}`}>{p.stock} in stock</p></div><Button variant="outline" size="sm" onClick={()=>edit(p)}><Pencil className="h-4 w-4 mr-2"/>Edit</Button>{p.active&&<Button variant="ghost" size="sm" onClick={()=>confirm('Archive this product?')&&archive.mutate(p._id)}><Archive className="h-4 w-4"/></Button>}</article>)}</div>:<div className="mt-6 grid gap-3">{!data.orders.length&&<div className="border border-dashed rounded-xl p-12 text-center text-muted-foreground">No store orders yet.</div>}{data.orders.map((o:any)=><article className="border rounded-xl p-5 bg-card grid md:grid-cols-[1fr_auto_auto] gap-5 items-center" key={o._id}><div><div className="flex gap-2 items-center"><strong>{o.orderNumber}</strong><span className={`text-xs px-2 py-1 rounded ${o.paymentStatus==='Paid'?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'}`}>{o.paymentStatus}</span></div><p className="text-sm mt-2">{o.user?.fullName||'Customer'} · {o.user?.email}</p><p className="text-sm text-muted-foreground">{o.items.map((i:any)=>`${i.quantity}× ${i.name}`).join(', ')}</p></div><strong>{money(o.total)}</strong><select className="border rounded px-3 py-2 bg-background" value={o.status} disabled={o.paymentStatus!=='Paid'} onChange={e=>status.mutate({id:o._id,status:e.target.value})}>{['Awaiting payment','Processing','Shipped','Delivered','Cancelled'].map(value=><option key={value}>{value}</option>)}</select></article>)}</div>}
 </div>
}
